(dp1
S'output'
p2
S"<type 'exceptions.NameError'> global name 'orderby' is not defined"
p3
sS'layer'
p4
S'/Users/kawasetakumi/Downloads/web2py/applications/myapp/controllers/blog.py'
p5
sS'code'
p6
S"# controllers/blog.py\ndef new():\n    form = SQLFORM(db.entry)\n    if form.accepts(request.vars,session):\n        redirect(URL(r=request,f='index'))\n    return dict(form=form)\n\ndef index():\n\trows = db(db.entry.id>0).select(orderby==db.entry.created_at)\n\treturn dict(rows=rows)\n\nresponse._vars=response._caller(index)\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/Users/kawasetakumi/Downloads/web2py/gluon/restricted.py", line 224, in restricted\n    exec ccode in environment\n  File "/Users/kawasetakumi/Downloads/web2py/applications/myapp/controllers/blog.py", line 12, in <module>\n  File "/Users/kawasetakumi/Downloads/web2py/gluon/globals.py", line 393, in <lambda>\n    self._caller = lambda f: f()\n  File "/Users/kawasetakumi/Downloads/web2py/applications/myapp/controllers/blog.py", line 9, in index\n    rows = db(db.entry.id>0).select(orderby==db.entry.created_at)\nNameError: global name \'orderby\' is not defined\n'
p11
s.